name: palette_extractor_ffi
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  file_picker: ^8.0.5
  flutter:
    sdk: flutter
    
  rust_plugin:
    path: plugins/rust_plugin

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
